"""
Machine Learning Module

This module trains a Random Forest classifier
to evaluate BUY signals generated by the
technical indicator voting engine.
"""

import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import StandardScaler
import joblib

from fetch_data import login, fetch_candles
from indicators import add_all_indicators
from signals import generate_signals

# ── Features Used By The Model 
"""
Features used by the Random Forest model.
These are derived from technical indicators.
"""

FEATURE_COLUMNS = [
    "rsi",
    "macd",
    "macd_signal",
    "macd_hist",
    "bb_percent",
    "bb_width",
    "adx",
    "adx_plus_di",
    "adx_minus_di",
    "atr",
    "volume_ratio",
    "ema_20",
    "ema_50",
    "sma_20",
    "sma_50",
    "vwap"
]

# ── Step 1: Label The Data 
def create_labels(df, forward_candles=5):
    """
    Create labels for every candle.

    Label:
        1 -> Price increased after forward_candles
        0 -> Price stayed same or decreased
    """

    # Future closing price
    df["future_close"] = df["close"].shift(-forward_candles)

    # Binary target
    df["target"] = (
        df["future_close"] > df["close"]
    ).astype(int)

    # Remove rows where future price is unavailable
    df = df.dropna(subset=["future_close"])

    return df


# ── Step 2: Prepare Training Data 
def prepare_training_data(df):

    available = [
        col for col in FEATURE_COLUMNS
        if col in df.columns
    ]

    missing = [
        col for col in FEATURE_COLUMNS
        if col not in df.columns
    ]

    if missing:
        print(f"Skipping missing features: {missing}")

    if len(available) < 5:
        print("Too few features.")
        return None, None

    # Remove rows with missing values
    dataset = df.dropna(subset=available + ["target"])

    X = dataset[available]
    y = dataset["target"].astype(int)

    print(f"Training samples : {len(dataset)}")
    print(f"Features         : {len(available)}")

    return X, y

# ── Step 3: Train The Model 
def train_model(X, y):
    # Check class distribution before splitting
    print(f"\nClass distribution:")
    print(f"  Good Signals (1): {(y == 1).sum()}")
    print(f"  Bad Signals  (0): {(y == 0).sum()}")

    # Split — use stratify to guarantee both classes appear in test set
    X_train, X_test, y_train, y_test = train_test_split(
        X, y,
        test_size=0.2,
        random_state=42,
        shuffle=True,
        stratify=y        # ← THIS is the key fix
    )

    # Scale features
    scaler  = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test  = scaler.transform(X_test)

    # Train Random Forest
    model = RandomForestClassifier(
        n_estimators=100,
        max_depth=5,
        random_state=42,
        class_weight="balanced"
    )
    model.fit(X_train, y_train)

    # Evaluate
    y_pred   = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)

    print(f"\nModel Accuracy: {accuracy * 100:.1f}%")

    # Safe classification report — only use classes that exist in test set
    present_classes = sorted(y_test.unique())
    class_names     = []
    if 0 in present_classes:
        class_names.append("Bad Signal")
    if 1 in present_classes:
        class_names.append("Good Signal")

    print("\nDetailed Report:")
    print(classification_report(
        y_test, y_pred,
        labels=present_classes,
        target_names=class_names
    ))
    print("\nTraining completed successfully.")

    # Feature Importance
    importance_df = pd.DataFrame({
        "Feature":    X.columns.tolist(),
        "Importance": model.feature_importances_
    }).sort_values("Importance", ascending=False)

    print("\nTop 5 Most Important Indicators:")
    print(importance_df.head(5).to_string(index=False))

    return model, scaler

# ── Step 4: Save The Model 
def save_model(
    model,
    scaler,
    model_path="model/model.pkl",
    scaler_path="model/scaler.pkl",
):
    joblib.dump(model, model_path)
    joblib.dump(scaler, scaler_path)
    print(f"\nModel saved  → {model_path}")
    print(f"Scaler saved → {scaler_path}")


# ── Step 5: Load The Model 
def load_model(
    model_path="model/model.pkl",
    scaler_path="model/scaler.pkl",
):
    model  = joblib.load(model_path)
    scaler = joblib.load(scaler_path)
    return model, scaler


# ── Step 6: Predict On New Signal 
def predict_signal_quality(model, scaler, row):
    """
    Given one row of live data, predict:
    - Will this BUY signal be profitable?
    - What is the confidence percentage?
    """
    features = row[FEATURE_COLUMNS].values.reshape(1, -1)
    features_scaled = scaler.transform(features)

    prediction   = model.predict(features_scaled)[0]
    probability  = model.predict_proba(features_scaled)[0]

    confidence   = probability[1] * 100    # probability of being a good signal

    return {
        "prediction":  "GOOD SIGNAL" if prediction == 1 else "WEAK SIGNAL",
        "confidence":  round(confidence, 1),
        "take_trade":  confidence >= 60    # only act if 60%+ confident
    }


# ── Full Pipeline 
def train_full_pipeline(df):
    """
    Runs the complete training pipeline on a DataFrame
    that already has indicators and signals added.
    """
    print("Labelling signals...")
    df = create_labels(df, forward_candles=10)

    print("Preparing training data...")
    X, y = prepare_training_data(df)
    if X is None:
        return None, None

    print(f"Training on {len(X)} BUY signals...")
    model, scaler = train_model(X, y)

    save_model(model, scaler)
    return model, scaler


